#include "gtest/gtest.h"
#include <iostream>
#include <iomanip>
#include <string>
#include <fstream>
#include <windows.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <cstdio>
//------------------------------------------------------------------------------
//Files we are testing:



//------------------------------------------------------------------------------

using namespace std;

//------------------------------------------------------------------------------
//          COPY BASIC_TEST INTO THIS FILE.
//                    AND THEN,
//         DO NOT EDIT THIS FILE ANY FURTHER
//------------------------------------------------------------------------------

bool remove_all(bool debug=false)
{
    ifstream ins;
    string path = "../../root/delete_all.txt";
    ins.open(path);
    if(ins.fail()) return false;
    string line;
    while(getline(ins, line))
    {
        rmdir(line.c_str());
        remove(line.c_str());
    }
    ins.close();
    ofstream out;
    out.open(path);
    if(out.fail()) return false;
    out.close();
    return true;
}

//Lord help me! 
const bool debug = false;

TEST(BASIC_TEST, BasicTest)
{
  bool success = remove_all(debug);
  EXPECT_EQ(success, true);
}


int main(int argc, char **argv)
{
  ::testing::InitGoogleTest(&argc, argv);
  std::cout<<"\n\n----------running---------\n\n"<<std::endl;
  return RUN_ALL_TESTS();
}